# Backup cron
MMC_MAIL_BACKUP_CRON_EXP: 30 4 * * * #every day at 4:30am
MMC_MAIL_BACKUP_TTL: 15 # Delete backups that are over 15 days

MMC_MAIL_FRESHCLAM_CRON_EXP: 0 4 * * *
MMC_MAIL_SPAMASSASSIN_UPDATE_CRON_EXP: 5 4 * * *
MMC_MAIL_SPAMASSASSIN_HAM_CRON_EXP: 10 4 * * *
MMC_MAIL_SPAMASSASSIN_SPAM_CRON_EXP: 15 4 * * *
